cask_args appdir: '/Applications'

brew 'awscli'
brew 'git'
brew 'htop'
brew 'jq'
brew 'node'
brew 'python'
brew 'kubectl'
brew 'kubectx'
brew 'kube-ps1'
brew 'rcm'

cask 'font-source-code-pro'
cask 'iterm2'
cask 'postman'
cask 'powershell'
cask 'visual-studio-code'